# Generated by Django 4.1 on 2022-08-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='the-7-best-books-to-improve-influencing-skills-2-scaled.jpg', null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
