# Generated by Django 4.1 on 2022-08-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='the-7-best-books-to-improve-influencing-skills-2-scaled.jpg', null=True, upload_to='%y/%m/%d'),
        ),
    ]
